Veewee::Session.declare({
  :cpu_count => '1',
  :memory_size=> '512',
  :disk_size => '10140',
  :disk_format => 'VDI',
  :hostiocache => 'on',
  :vm_options => {
    :ioapic => 'on',
    :pae    => 'on',
  },
  :os_type_id => 'Ubuntu_64',
  :iso_file => "ubuntu-12.04.3-minimal-amd64.iso",
  :iso_src => "http://archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/current/images/netboot/mini.iso",
  :iso_md5 => '1278936cb0ee9d9a32961dd7743fa75c',
  :iso_download_timeout => "1000",
  :boot_wait => "9",
  :boot_cmd_sequence => [
    '<Esc><Esc>',
    'linux noapic preseed/url=http://%IP%:%PORT%/ece-u12.seed ',
    'debian-installer=en_US auto locale=en_US kbd-chooser/method=us ',
    'hostname=%NAME% ',
    'fb=false debconf/frontend=noninteractive ',
    'keyboard-configuration/layout=USA keyboard-configuration/variant=USA console-setup/ask_detect=false ',
    'initrd=initrd.gz -- <Enter>'
],
  :kickstart_port => "7122",
  :kickstart_timeout => "10000",
  :kickstart_file => "ece-u12.seed",
  :ssh_login_timeout => "10000",
  :ssh_user => "root",
  :ssh_password => "",
  :ssh_key => "ecasp",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => "shutdown -P now",
  :postinstall_files => [ "postinstall.sh"],
  :postinstall_timeout => "10000"
})
